### PR TITLE
Allow to use SPI0 and SPI1

### PR DESCRIPTION
**Pull request by caveman99**

### CODE REVIEW

**Comment by beegee-tokyo** [comment]
Hello @caveman99 
Thank you for your contribution, but as this library is written specifically for the RAK13800 of our WisBlock product line your changes do not make much sense. The WisBlock Core modules support only one SPI.

**Comment by caveman99** [comment]
This change was needed for me to get the module working on the RAK 4631 with the meshtastic firmware. Without the change it just says there's no module installed. 'SPI' is used to access the Lora Radio, which is on a different (internal) SPI bus. I have to use this patch with an init of 'SPI1' to get an address and use MQTT...

**Comment by beegee-tokyo** [comment]
@caveman99 
Can you check new release V1.0.2?

Changes were included with https://github.com/RAKWireless/RAK13800-W5100S/commit/1e2a3f136a1b3825121208d8c997c5ddbc7d8b05

**Comment by caveman99** [comment]
@beegee-tokyo works perfectly, thanks for including this! I'll change the lib ref in the firmware now...

**Pull request closed without merging**
